Repository Coder-forfun/hacktoberfest, pull requests merged in 2022-10, with the labels that each got.

#1 Create precision.java
  precision.java
Labels: hacktoberfest-accepted, hacktoberfest-accepted.

#2 Update README.md
  README.md
Labels: good first issue, hacktoberfest-accepted, hacktoberfest-accepted.

#3 Tic tac toe
  TicTacToe.java
Labels: hacktoberfest-accepted
